// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS8ERZdUISJ8izz4Iw5YVSEFfsG5sDjIg',
    appId: '1:755362521413:web:747e8cad5da51470fc9e2c',
    messagingSenderId: '755362521413',
    projectId: 'ewallet-520db',
    authDomain: 'ewallet-520db.firebaseapp.com',
    storageBucket: 'ewallet-520db.firebasestorage.app',
    measurementId: 'G-DRH2TQWGY6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXdEtpSBPt73WtPGaMbpjc0_CSdYOmBLg',
    appId: '1:755362521413:android:9481859fead5c60dfc9e2c',
    messagingSenderId: '755362521413',
    projectId: 'ewallet-520db',
    storageBucket: 'ewallet-520db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDelRsLyuFULkzZe0MbvERQx8ecleCk09A',
    appId: '1:755362521413:ios:0f64d757122fde10fc9e2c',
    messagingSenderId: '755362521413',
    projectId: 'ewallet-520db',
    storageBucket: 'ewallet-520db.firebasestorage.app',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDelRsLyuFULkzZe0MbvERQx8ecleCk09A',
    appId: '1:755362521413:ios:0f64d757122fde10fc9e2c',
    messagingSenderId: '755362521413',
    projectId: 'ewallet-520db',
    storageBucket: 'ewallet-520db.firebasestorage.app',
    iosBundleId: 'com.example.ewallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS8ERZdUISJ8izz4Iw5YVSEFfsG5sDjIg',
    appId: '1:755362521413:web:769736047e650f7afc9e2c',
    messagingSenderId: '755362521413',
    projectId: 'ewallet-520db',
    authDomain: 'ewallet-520db.firebaseapp.com',
    storageBucket: 'ewallet-520db.firebasestorage.app',
    measurementId: 'G-63S51RH193',
  );
}
